media: media/images
content:
  - name: weapons
    label: Weapons
    path: data/weapons
    filename: '{primary}.json'
    type: collection
    view:
      fields: [ item.image, item.name, item.tags, wa, con, avail, ammo, shots, rof, rel, range, item.cost, item.src ]
      primary: name
    fields:
      - { name: item, label: ITEM, component: item }
      - { name: wa, label: WA, type: number }
      - { name: con, label: CON, type: select, options: { values: [ P, J, L, N ] }}
      - { name: avail, label: AVAIL, type: select, options: { values: [ E, C, P, R ] }}
      - { name: damage, label: DAMAGE, type: string }
      - { name: ammo, label: AMMO, type: reference, options: { collection: ammunition}}
      - { name: shots, label: SHOTS, type: number }
      - { name: rof, label: ROF, type: number }
      - { name: burst, label: BURST, type: boolean }
      - { name: rel, label: REL, type: select, options: { values: [ UR, ST, VR ] }}
      - { name: range, label: RANGE, type: number }
  - name: ammunition
    label: Ammunition
    path: data/ammunition
    filename: '{primary}.json'
    type: collection
    view:
      fields: [ item.name, item.tags, caliber, damage, damageType, avail, item.cost, item.src ]
      primary: name
    fields:
      - { name: item, label: ITEM, component: item }
      - { name: caliber, label: CALIBER, type: string }
      - { name: damage, label: DAMAGE, type: string }
      - { name: damageType, label: DAMAGE TYPE, type: string }
      - { name: avail, label: AVAIL, type: select, options: { values: [ E, C, P, R ] }}

components:
  item:
    label: item
    type: object
    fields:
      - { name: id, label: ID, type: uuid, hidden: true, options: { editable: false }}
      - { name: name, label: NAME, type: string, required: true }
      - { name: tags, label: TAGS, type: string, list: { min: 1, collapsible: false }}          
      - { name: image, label: IMAGE, type: image }
      - { name: cost, label: COST, type: number }
      - { name: note, label: NOTE, type: rich-text }
      - { name: src, label: SRC, type: string}
      - { name: homebrew, label: HOMEBREW, type: boolean }