media: media/images
content:
  - name: weapons
    label: Weapons
    path: data/weapons
    filename: '{primary}.json'
    type: collection
    fields:
      - { name: weapon, label: WEAPON, component: ranged-weapon }

components:
  item:
    type: object
    fields:
      - { name: id, label: ID, type: uuid, hidden: true, options: { editable: false }}
      - { name: name, label: NAME, type: string, required: true }
      - { name: tags, label: TAGS, type: string, list: { min: 1, collapsible: false }}          
      - { name: image, label: IMAGE, type: image }
      - { name: cost, label: COST, type: number }
      - { name: note, label: NOTE, type: rich-text }
      - { name: src, label: SRC, type: string}
      - { name: homebrew, label: HOMEBREW, type: boolean }
  weapon:
    component: item
    fields:     
      - { name: wa, label: WA, type: number }
      - { name: con, label: CON, type: select, options: { values: [ P, J, L, N ] }}
      - { name: avail, label: AVAIL, type: select, options: { values: [ E, C, P, R ] }}
      - { name: damage, label: DAMAGE, type: string }
      - { name: rel, label: REL, type: select, options: { values: [ UR, ST, VR ] }}
  ranged-weapon:
    component: weapon
    fields:
      - { name: ammo, label: AMMO, type: string }
      - { name: shots, label: SHOTS, type: number }
      - { name: rof, label: ROF, type: number }
      - { name: burst, label: BURST, type: boolean }
      - { name: range, label: RANGE, type: number }