media: files/media
content:
  - name: data
    label: DATA
    path: data.json
    type: collection
    fields:
      - name: id
        label: ID
        type: string
        required: true
      - name: name
        label: NAME
        type: string
        required: true
      - name: tags
        label: TAGS
        type: string
        list:
          collapsible: false
