media: media/images
content:
  - name: data
    label: DATA
    path: data
    filename: '{primary}.json'
    type: collection
    view:
      fields: [ image, name, tags ]
      primary: name
      sort: [ name, tags ]
    fields:
      - { name: id, label: ID, type: string, required: true }
      - { name: name, label: NAME, type: string, required: true }
      - { name: tags, label: TAGS, type: string, list: { min: 1, collapsible: false }}          
      - { name: image, label: IMAGE, type: image }
      - { name: note, label: NOTE, type: rich-text }